## **Basic Array Operations:**
Q1. Create a 3x3 array filled with random integers between 0 and 10.
Then calculate the sum, mean, and standard deviation of the array.

In [ ]:
import numpy as np
array = np.random.randint(0, 11, size=(3, 3))


In [ ]:
print(array)


[[ 5  8  8]
 [ 7  6  0]
 [10  9  0]]


In [ ]:
print("Sum:", np.sum(array))


Sum: 53


In [ ]:
print("Mean:",np.mean(array))

Mean: 5.888888888888889


In [ ]:
print("Standard deviation", np.std(array))

Standard deviation 3.4462360931712936


Q2. Create a 1D array of 10 elements and compute the cumulative sum.

In [ ]:
import numpy as np
array_1d = np.arange(1,11)
print("Original array:", array_1d)
cumulative_sum = np.cumsum(array_1d)
print("cumulative_sum:", np.cumsum(array_1d))

Original array: [ 1  2  3  4  5  6  7  8  9 10]
cumulative_sum: [ 1  3  6 10 15 21 28 36 45 55]


Q3.Generate two 2x3 arrays with random integers and perform element-wise addition,
subtraction, multiplication, and division.


In [ ]:
A = np.random.randint(1,10,(2,3))
B = np.random.randint(1,10,(2,3))
print("Array A:\n",A)
print("Array B:\n",B)

print("Addition:\n", A + B)
print("Substraction:\n", A - B)
print("Division:\n", A / B)
print("Multiplication:\n", A * B)

Array A:
 [[4 1 5]
 [6 8 7]]
Array B:
 [[9 9 5]
 [5 1 7]]
Addition:
 [[13 10 10]
 [11  9 14]]
Substraction:
 [[-5 -8  0]
 [ 1  7  0]]
Division:
 [[0.44444444 0.11111111 1.        ]
 [1.2        8.         1.        ]]
Multiplication:
 [[36  9 25]
 [30  8 49]]


Q4.Create a 4x4 identity matrix.

In [ ]:
identify_matrix = np.eye(4)
print("4*4 Identify matrix:")
print(identify_matrix)

4*4 Identify matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Q5. Given an array a = np.array([5, 10, 15, 20, 25]), divide each element by 5 using broadcasting.


In [ ]:
a = np.array([5,10,15,20,25])
result = a/5 # broadcast happens here
print("Original array:",a)
print("After division:", result)

Original array: [ 5 10 15 20 25]
After division: [1. 2. 3. 4. 5.]


# **Array Manipulation:**
Q6. Reshape a 1D array of 12 elements into a 3x4 matrix

In [ ]:
Array_1d = np.arange(1,13)
Array_reshaped = Array_1d.reshape(3,4)
print("\n Reshaped_array:")
print(Array_reshaped)


 Reshaped_array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


7. Flatten a 3x3 matrix into a 1D array.

In [ ]:
matrix_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original 3d matrix")
print(matrix_2d)
flattened_array = matrix_2d.flatten()
print("\n Flattened 1d array")
print(flattened_array)

Original 3d matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 Flattened 1d array
[1 2 3 4 5 6 7 8 9]


8. Stack two 3x3 matrices horizontally and vertically.

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[10,11,12],[13,14,15],[16,17,18]])
print("Matrix a:")
print(a)
print("Matrix b:")
print(b)
vertical_stack = np.vstack((a,b))
print("\n Vertically stacked (shape{}):".format(vertical_stack.shape))
print(vertical_stack)
horizontal_stack = np.hstack((a,b))
print("\n Horizontally stacked (shape{}):".format(horizontal_stack.shape))
print(horizontal_stack)

Matrix a:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix b:
[[10 11 12]
 [13 14 15]
 [16 17 18]]

 Vertically stacked (shape(6, 3)):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

 Horizontally stacked (shape(3, 6)):
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


9. Concatenate two arrays of different sizes along a new axis

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5])
a_reshaped = a[:,np.newaxis]
b_reshaped = b[:,np.newaxis]
combined = np.concatenate((a_reshaped,b_reshaped), axis=0)
print("\n concatenated array alon new axis(axis=0):")
print(combined)
print("shape:", combined.shape)


 concatenated array alon new axis(axis=0):
[[1]
 [2]
 [3]
 [4]
 [5]]
shape: (5, 1)


10. Transpose a 3x2 matrix and then reshape it to have 3 rows and 2 columns.

In [ ]:
import numpy  as np
original_matrix = np.array([[1,2],[3,4],[5,6]])
print("original matrix:")
print(original_matrix)
print("shape:", original_matrix.shape)
transposed_matrix = np.transpose(original_matrix)
print("\n Transposed matrix:")
print(transposed_matrix)
print("shape:", transposed_matrix.shape)
reshaped_matrix = transposed_matrix.reshape(3,2)
print("\n Reshaped matrix:")
print(reshaped_matrix)
print("shape:", reshaped_matrix.shape)

original matrix:
[[1 2]
 [3 4]
 [5 6]]
shape: (3, 2)

 Transposed matrix:
[[1 3 5]
 [2 4 6]]
shape: (2, 3)

 Reshaped matrix:
[[1 3]
 [5 2]
 [4 6]]
shape: (3, 2)


# **Indexing and Slicing:**
11. Given a 1D array of 15 elements, extract elements at positions 2 to 10 with a step of 2.

In [ ]:
array = np.arange(1,16)
print("Original array:")
print(array)
sliced_array = array[2:10:2]
print("n\sliced elements(from index 2 to 10, step 2)")
print(sliced_array)

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
n\sliced elements(from index 2 to 10, step 2)
[3 5 7 9]


12. Create a 5x5 matrix and extract the sub-matrix containing elements from rows 1 to 3 and
columns 2 to 4.

In [ ]:
matrix = np.arange(1,26).reshape(5,5)
print("5x5 Matrix:")
print(matrix)
submatrix = matrix[1:4,2:5]
print("\n Extracted submatrix:")
print(submatrix)

5x5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 Extracted submatrix:
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


13. Replace all elements in a 1D array greater than 10 with the value 10.

In [ ]:
array = np.array([3,7,11,15,2,10,13,5])
print("oRIGINAL Array:")
print(array)
array[array>10]=10
print("\n Modified array:" )
print(array)

oRIGINAL Array:
[ 3  7 11 15  2 10 13  5]

 Modified array:
[ 3  7 10 10  2 10 10  5]


14. Use fancy indexing to select elements from a 1D array at positions [0, 2, 4, 6]

In [ ]:
array = np.arange(1,11)
print("original array:")
print(array)
fancy_selected = array[[0,2,4,6]]
print("\n fancied index array ")
print(fancy_selected)

original array:
[ 1  2  3  4  5  6  7  8  9 10]

 fancied index array 
[1 3 5 7]


15. Create a 1D array of 10 elements and reverse it using slicing.

In [ ]:
array = np.arange(1,11)
print("\n Original array:", array)
reversed_array = array[::-1]
print("\n Reversed array:", reversed_array)


 Original array: [ 1  2  3  4  5  6  7  8  9 10]

 Reversed array: [10  9  8  7  6  5  4  3  2  1]


# **Broadcasting:**
16. Create a 3x3 matrix and add a 1x3 array to each row using broadcasting.

In [ ]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
row_array = np.array([10,20,30])
result = matrix+row_array
print("original matrix")
print(matrix)
print("\n row array")
print(row_array)
print("\n result after broadcasting:")
print(result)

original matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 row array
[10 20 30]

 result after broadcasting:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


17. Multiply a 1D array of 5 elements by a scalar value using broadcasting.

In [ ]:
array = np.array([1,2,6,8,10])
scalar =3
result = array*scalar
print("original array:")
print(array)
print("\n result after broadcasting:")
print(result)

original array:
[ 1  2  6  8 10]

 result after broadcasting:
[ 3  6 18 24 30]


18. Subtract a 3x1 column vector from a 3x3 matrix using broadcasting.

In [ ]:
matrix = np.array([[100,90,80],[70,60,50],[40,30,20]])
column_vector = np.array([[5],[2],[6]])
result = matrix - column_vector
print("original matrix:")
print(matrix)
print("\n column vector:")
print(column_vector)
print("\n result after broadcasting:")
print(result)

original matrix:
[[100  90  80]
 [ 70  60  50]
 [ 40  30  20]]

 column vector:
[[5]
 [2]
 [6]]

 result after broadcasting:
[[95 85 75]
 [68 58 48]
 [34 24 14]]


19. Add a scalar to a 3D array and demonstrate how broadcasting works across all dimensions?

In [ ]:
array_3d = np.arange(24).reshape(2,3,4)
print("original 3d array(shape{}):".format(array_3d.shape))
print(array_3d)
scalar = 5
result = array_3d + scalar
print("\n result after broadcasting:")
print(result)

original 3d array(shape(2, 3, 4)):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

 result after broadcasting:
[[[ 5  6  7  8]
  [ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]
  [25 26 27 28]]]


20. Create two arrays of shapes (4, 1) and (1, 5) and add them using broadcasting.

In [ ]:
a = np.array([[1],[2],[3],[4]])
b = np.array([[10,20,30,40,50]])
result = a+b
print("Array a:")
print(a)
print("\n Array b:")
print(b)
print("\n result after broadcasting:")
print(result)

Array a:
[[1]
 [2]
 [3]
 [4]]

 Array b:
[[10 20 30 40 50]]

 result after broadcasting:
[[11 21 31 41 51]
 [12 22 32 42 52]
 [13 23 33 43 53]
 [14 24 34 44 54]]


# **Vectorized Operations:**
21. Compute the square root of each element in a 2D array using vectorized operations

In [ ]:
import numpy as np
array = np.array([[1,4,9],[16,25,36],[49,64,81]])
print("Original Array:")
print(array)
sqrt_array = np.sqrt(array)
print( "\nSquare root of each element:")
print(sqrt_array)

Original Array:
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

Square root of each element:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


22. Calculate the dot product of two 1D arrays of size 5.

In [ ]:
a = np.array([3,5,8,6,1])
b = np.array([4,2,5,1,9])
print("Array a:")
print(a)
print("array b:")
print(b)
dot_product = np.dot(a,b)
print("\n dot product of a and b is ", dot_product)

Array a:
[3 5 8 6 1]
array b:
[4 2 5 1 9]

 dot product of a and b is  77


23. Perform element-wise comparison of two 1D arrays and return an array of boolean values
indicating where the first array has larger elements.

In [ ]:
a = np.array([10,3,6,4,9])
b = np.array([9,4,8,2,7])
print("array a:")
print(a)
print("array b:")
print(b)
comparision_result = a>b
print("\n comparision result:")
print(comparision_result)

array a:
[10  3  6  4  9]
array b:
[9 4 8 2 7]

 comparision result:
[ True False False  True  True]


24. Create a 2D array and apply a vectorized operation to double the value of each element.


In [ ]:
array_2d = np.array([[4,3,2,7],[7,4,9,1],[5,6,8,4]])
print("original 2d array:")
print(array_2d)
doubled_array = array_2d*2
print("\n array after doubling:")
print(doubled_array)
#

original 2d array:
[[4 3 2 7]
 [7 4 9 1]
 [5 6 8 4]]

 array after doubling:
[[ 8  6  4 14]
 [14  8 18  2]
 [10 12 16  8]]


25. Create a 1D array of 100 random integers and compute the sum of all even numbers using
vectorized operations

In [ ]:
array = np.random.randint(1,100, size=100)
print("original array:")
print(array)
even_numbers = array[array%2==0]
print("\n even numbers:")
print(even_numbers)
sum_even_numbers = np.sum(even_numbers)
print("\n sum of even numbers:", sum_even_numbers)

original array:
[77 25 61 55 34 79 80 23 69 59 13 34 33 65 54 49 47 99  4 23 95 27 18 68
 90 30 21 34 89 50 87  4 44 32 37 99 36 55 29 78 47 30 41 74 96 26 69 96
 83 93 20 11 27 41 72 27 56 71 14  8 95 53  7 85 96 50 77 43 94 11 83 15
 21 56 60 95 66 91  7 99 42 92  8 38 60  7 53 45 68  1 81 89 81 71 20 37
  7 83 11 62]

 even numbers:
[34 80 34 54  4 18 68 90 30 34 50  4 44 32 36 78 30 74 96 26 96 20 72 56
 14  8 96 50 94 56 60 66 42 92  8 38 60 68 20 62]

 sum of even numbers: 1994


# **Linear Algebra:**
26. Create a 3x3 matrix and find its determinant

In [2]:
import numpy as np
a = np.array([[2,7,4],[-1,4,5],[12,9,3]])
print("original matrix:")
print(a)
det_a = np.linalg.det(a)
print("\n determinant of a is:", det_a)

original matrix:
[[ 2  7  4]
 [-1  4  5]
 [12  9  3]]

 determinant of a is: 146.99999999999997


27.Given a 2x2 matrix, compute its inverse and verify by multiplying with the original matrix to
obtain the identity matrix.

In [6]:
import numpy as np
A = np.array([[6,3],[2,8]])
det = np.linalg.det(A)
print("\n Determinant : ", det )
inv_det = np.linalg.inv(A)
print("\n Inverse:",inv_det)
I_check = np.dot(A,inv_det)
print("\n Identity check:")
print(I_check)


 Determinant :  41.999999999999986

 Inverse: [[ 0.19047619 -0.07142857]
 [-0.04761905  0.14285714]]

 Identity check:
[[1. 0.]
 [0. 1.]]


28. Calculate the eigenvalues and eigenvectors of a 2x2 matrix.

In [7]:
A = np.array([[4,9],[3,5]])
print("Matrix A:")
print(A)
eigenvalues, eigenvectors = np.linalg.eig(A)
print("\n Eigenvalues:")
print(eigenvalues)
print("\n Eigenvectors:")
print(eigenvectors)

Matrix A:
[[4 9]
 [3 5]]

 Eigenvalues:
[-0.72015325  9.72015325]

 Eigenvectors:
[[-0.88559411 -0.84396375]
 [ 0.46445999 -0.53640022]]


29. Solve the system of linear equations 2x + 3y = 5 and 4x + 6y = 10 using NumPY

In [8]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, 3],
              [4, 6]])

# Constants vector B
B = np.array([5, 10])

# Try solving the system
try:
    X = np.linalg.solve(A, B)
    print("Unique solution:", X)
except np.linalg.LinAlgError as e:
    print("No unique solution:", e)


No unique solution: Singular matrix


30. Perform Singular Value Decomposition (SVD) on a 3x3 matrix and reconstruct the original
matrix using the SVD componen

In [9]:
A = np.array([[3, 1, 1],
              [-1, 3, 1],
              [0, 2, 4]])

print("Original Matrix A:")
print(A)

# Step 2: Perform SVD
U, S, VT = np.linalg.svd(A)

print("\nU Matrix:")
print(U)

print("\nSingular values (as 1D array):")
print(S)

print("\nV Transpose (V^T):")
print(VT)

# Step 3: Convert S into a diagonal matrix (same shape as A)
S_matrix = np.zeros_like(A, dtype=float)
np.fill_diagonal(S_matrix, S)

# Step 4: Reconstruct A from SVD components
A_reconstructed = U @ S_matrix @ VT

print("\nReconstructed Matrix A:")
print(A_reconstructed)

# Step 5: Compare (optional)
print("\nIs close to original? →", np.allclose(A, A_reconstructed))


Original Matrix A:
[[ 3  1  1]
 [-1  3  1]
 [ 0  2  4]]

U Matrix:
[[-0.31100366  0.87599752 -0.36865304]
 [-0.48917824 -0.48010545 -0.72815067]
 [-0.81485052 -0.04612048  0.57783348]]

Singular values (as 1D array):
[5.3191452  3.18371454 1.88961798]

V Transpose (V^T):
[[-0.08344061 -0.64074946 -0.76320233]
 [ 0.97624896 -0.20622445  0.06640362]
 [-0.19993906 -0.73953472  0.64273849]]

Reconstructed Matrix A:
[[ 3.00000000e+00  1.00000000e+00  1.00000000e+00]
 [-1.00000000e+00  3.00000000e+00  1.00000000e+00]
 [ 6.30479096e-16  2.00000000e+00  4.00000000e+00]]

Is close to original? → True
